version: '3.8'

services:
  app:
    image: maven:3.8.7-eclipse-temurin-8
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        mvn clean compile spring-boot:run
      "
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge